spring:
  datasource:
    url: jdbc:mysql://localhost:3306/throne_prod
    username: throne_prod_user
    password: throneprod
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect






